services:
  postgres:
    container_name: "postgres"
    image: postgres:16.3
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - docker/postgres.env
volumes:
  postgres_volume:
    driver: local